FROM docker.io/kalilinux/kali-rolling
RUN apt-get update && apt-get install -y \
    fish \
    git \
    curl \
    wget \
    sudo \
    procps \
    hostname \
    passwd \
    util-linux \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
