hl.on("hyprland.start", function()
    hl.exec_cmd("quickshell")
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("sh -c 'swaybg -i \"$(cat $HOME/.cache/current-wallpaper)\" -m fill &'")
    hl.dispatch(hl.dsp.focus({ workspace = wsStart }))
end)